---
title: "Five observations on the last five years of contact hypothesis research"
subtitle: "A retrospective on 'The Contact Hypothesis Re-evaluated'"
author: "Seth Green"
abstract: "This article provides five policy-oriented observations on the state of contact hypothesis research five years after the publication of 'The Contact Hypothesis Re-evaluated'. I argue that that paper's overall assessment that contact 'typically works', but with significant caveats regarding ...some other stuff"
thanks: "Thanks to Matt Lowe, Betsy Levy Paluck, Don Green, Réka Bodo, and Roni Porat for conversations that inspired this piece."
wordcount: 1000
bibliography: TCHR-refs.bib
titlepage: true
numbersections: true
output: draft::working_paper
knit: draft::knit_with_appendices
---

# 1 Introduction: The contact hypothesis, seventy years later

Seventy years on, Gordon Allport's 'The Nature of Prejudice' remains seminal. Perhaps its most influential idea is 'the contact hypothesis,' the idea that contact between groups can help reduce tensions between them. However, Allport did not believe that just any contact would do, and was careful to distinguish between "casual contact" and "true acquaintance" [@allport1954, p. XXX]. In order to have true acquaintance, Allport argued, contact needed to meet four additional conditions: the support of authorities, shared goals, cooperation, and equal status. This theory would predict that, for instance, sharing a commuter rail station with Latino immigrants would do nothing to decreases whites' anti-immigrant sentiments [@enos2014], while being assigned to play cricket with a member of a different caste \textemdash a setting where the four conditions are met \textemdash would reduce hostilities [@lowe2021].

Nearly two decades ago, an influential meta-analysis by @pettigrew2006 reviewed hundreds of contact studies, comprising hundreds of thousands of subjects, and found that contact "typically reduces intergroup prejudice" (p. 751). Moreover, Allport's facilitating conditions were evidently not necessary for positive effects: “samples with no claim to these key conditions still show significant relationships between contact and prejudice” (p. 766). Overall, they write, “[t]here is little need to demonstrate further contact's general ability to lessen prejudice. Results from the meta-analysis conclusively show that intergroup contact can promote reductions in intergroup prejudice” (p. 751).

Five years ago, my colleagues and I published 'The contact Hypothesis Re-evaluated' [@paluck2019], an updated meta-analysis with an amended methodological focus. Rather than looking at the entirety of contact literature, we focused exclusively on randomized controlled trials with at least a day of delay between the commencement of treatment and outcome measurement.

In the main, we found that contact did indeed typically reduce prejudice in the assembled studies, reinforcing the central contention of @pettigrew2006. However, we also uncovered four grounds for skepticism about when and where worked did its magic.

First, our measured effect sizes were not robust to two measures of study quality. In our sample, the larger the study, the smaller the effect, and studies with pre-analysis plans had a tiny, null effect on average. Second, there was significant heterogeneity between targets of prejudice. The most effective interventions were those aimed at reducing prejudice against people with disabilities, while studies aimed at ethnic, racial, religious and anti-immigrant sentiment were generally less effective, though still statistically significant on average. Third, we found lacunae. The most troubling was the total absence of studies looking at interracial prejudice in people over 25. Fourth, there were no systematic variations of Allport's facilitating conditions.

It has now been five years since that piece was published, and eight since we stopped collecting data. The question of what reduces prejudice between groups has not lost any of its urgency and vitality. So what have we learned since then?

# A welcome proliferation of field experiments (that find mixed effects)

Our meta-analysis was fortuitously timed in that it coincided with the publication of some very impressive papers featuring rigorous and naturalistic tests of contact in settings where assuaging tensions is of the utmost importance. Two notable papers used intergroup sports to get groups to cooperate: inter-caste cricket in India [@lowe2021] or soccer for Christians and Muslims in Iraq [@mousa2020]. Another is educational settings, e.g. pairing "minority Roma and majority non-Roma Hungarians" students' desk pairings [@elwert2023] or native-born Austrians and refugees for a school-based workshop on fleeing one's home and prejudice [@nagele2023]. Finally, @grady2023 tested a contact intervention, led by Mercy Corps, intended to bridge divides between farmers and pa storalists in middle belt Nigeria, the site of prior violent conflict. These studies build on the latest, most rigorous studies that we meta-analyzed (e.g. @scacco2018, @broockman2016) in forming a new standard for contact experiments.

They also find disconcertingly mixed effects. @lowe2021 finds that playing together creates new friendships and reduces ingroup favoritism, but @elwert2023 find, essentially, no results. @mousa2021 finds positive effects within the context of soccer, but very little that generalized. @nagele2023 find positive effects, but also found positive effects for the version of the intervention that did not have contact. Finally @grady2023 found positive effects on stated attitudes, but no detectable effects on behaviors.

To the contact hypothesis's most avid boosters, I ask: what is going on here? If contact typically reduces prejudice \textemdash if we can "answer the question of whether contact reduces prejudice “with an emphatic ‘yes’” [@hewstone2003panacea, p. 352], then what went wrong or differently in these settings? Our meta-analysis inspired some rather critical rejoinders, e.g. @pettigrew2021, but truly, it is these studies, and their middling findings, that most call out for an explanation.

Here is my theory.

# Not all forms of 'prejudice' are alike

In its plain language use, the word 'prejudice' connotes 'pre-judgment:' assessing someone before you know them based on group characteristics. In this sense, prejudice stems from a lack of experience.

In our meta-analysis, the most effective interventions are aimed at prejudices that plausibly be attributed to ignorance: people who are old [@meshel2004] or blind [@evans1976], or coworkers with intellectual disabilities [@ditullio1982]. But the same cannot be said about @scacco2018, where members of both groups experienced racial riots, or @mousa2020, where Christians had recently experienced ethnic cleansing at the hands of the Islamic State.

We need richer language than just 'prejudice' for the many feelings that intergroup friction might engender. For instance, we might use

-   **prejudice** for negative feelings that can plausibly be attributed to ignorance or a lack of experience;

-   **hostility** for people who have negative but non-violent experiences with the outgroup ( e.g. the use of derogatory language);

-   **animus** for people who have experienced the worst kinds of intergroup contact, such as sustained discrimination and violence.

My working theory is that intergroup contact is effective at reducing prejudice; moderately effective at reducing hostility; and not likely to affect animus.

It seems impolite and unscholarly to observe that some forms of antipathy are better justified than others. But I think each of us intuitively knows this to be true. If I could ask my ancestor who fled pogroms how they felt about their persecutors, I think they would say some very unpleasant things. I do not think that playing in a sports league with their persecutors' compatriots would have changed their overall attitudes very much, though I can imagine them calling a favored teammate "one of the good ones." Some negative feelings probably only recede when a generation passes on, or, after an extraordinary period of sustained cooperation [@jha2013; @jha2019].

In this light, we might try to extend empathy, or at least an anthropologically-minded neutrality, towards the subjects in @mousa2020, despite the fact that 40% of them believe the outgroup to be cursed.

# The unknown role of assimilation

In the 1990s, queer theorists had a lively debate about whether gay marriage was a worthy goal. While @warner1999 notes that even raising the issue can make one "feel like the unmannerly wedding guest" (p. 120), many "veterans of earlier forms of gay activism" would rank marriage as a much lower priority than "HIV and health care, AIDS prevention, the repeal of sodomy laws, antigay violence, job discrimination, immigration, media coverage, military antigay policy, sex inequality, and the saturation of everyday life with heterosexual privilege" (p. 120-121). More fundamentally, he argues, "marriage has become the central legitimating institution by which the state penetrates the sexuality of its subjects; it is the “zone of privacy” outside which sex is unprotected" (p. 128).

In the end, the gay marriage movement was thoroughly victorious. But within Warner's cricticism is a deep point about the tradeoffs inherent to assimilation. The modern gay rights movement chose a profoundly integrationist goal as its masthead: a vision of gays and lesbians moving to the suburbs to raise kids over the wilder, more liberationist vision of a utopia of bathhouses, parades, and a shared commitment to rejecting heteronormativity. This collective choice to assimilate, to put a less weird face forward, strikes me as explaining much of the success of the movement in changing American attitudes. (The AIDS crisis is also a large part of the turn to normativity, though outside the scope of this article.)

This also seems to me to be one of the key unexplored moderators of when and where contact reduces prejudice. We know that a brief conversation with a cisgendered or trans canvasser about trans rights can reduce anti-trans attitudes for at least 3 months [@broockman2016], with trans canvassers producing more positive effects on average. Does it matter how well they 'pass' as cis, how assimilated their gender performance is? How about whether they are advocating for an integrationist policy change, such as healthcare rights, versus a socially disruptive one, like competition in youth sports?[^1]

[^1]: On the question of trans participation in youth sports in particular, there has been some exploratory observational work [@goldbach2022; @tanimoto2021], but to the best of my knowledge, no experimental tests.

Likewise with antisemitism, which has renewed importance in American public life of late. Around 14% of Jews are Haredi, or strictly orthodox [@staetsky2022], and are generally recognizable as such because of a shared commitment to highly visible forms of non-assimilation. Will contact with less observant Jews produce tolerance for the Haredi or vice versa? Does degree of assimilation of the person whose presence provides a contact intervention affect degree of outgroup tolerance?

These questions seem worth exploring further in empirical work as we continue to search for the moderating effects of intergroup contact.

# Light touch interventions for light prejudice

In parallel to the proliferation of contact field experiments, many scholars are pursuing what my colleagues call 'light touch interventions' [@paluck2021]], defined by being quick, easy to implement, and cheap. For instance, we have a plethora of studies in which subject imagine contact [@crisp2012], experience it vicariously [@mazziotta2011], and/or online [@bond2023; @stelzmann2021].

These light touch interventions seem well-suited for the lightest forms of prejudice: those least grounded in negative experiences. Negative feelings towards people with schizophrenia [@stelzmann2021] or women on the autism spectrum [@redquest2022] are plausibly explained by ignorance, and seem amenable to light touch contact. However, sustained negative prior experiences with an outgroup seem unlikely to be outweighed or countermanded by a light touch rejoinder.

# We still need systematic tests of the facilitating conditions

@elwert2023, who tested the effect of pairing non-Roma and Roma Hungarian students' seating, produced results that I, and other Americans I've spoke to, considered disappointing and surprising. When I shared the results with a Hungarian friend, she asked, in effect: yes but how were the Roma students treated by teachers? Were they seated in the back, never called on, or otherwise not given equal status? As the authors put it, "equal status as students within the formal framework of Hungarian education may not prevent community prejudice from inflecting interactions among students, or between students and teachers, much like randomly assigning college roommates does not prevent social hierarchies from entering dorm rooms" (p. 14). In other words, we do not know how well Allport's four facilitating conditions were adhered to.

This is a familiar problem. As my co-authors and I noted in our previous meta-analysis, there was a distinct "lack of experiments that systematically test the moderating impact of these conditions on prejudice reduction" [@paluck2019, p. 153] . We also noted "a general lack of detailed description about the interventions" which made it hard to determine it was particularly difficult to determine whether an intervention involved equal status or a common goal "(p. 141). It seems that these problems have persisted, likely because they are hard (the more naturalistic a field experiment, the less a researcher can hope to control individual interactions). Nevertheless, I would love to see more attention to systematic variations in the facilitating conditions.
